{{- if .Values.orchestrator.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ printf "%s-hpa" .Values.orchestrator.workersName }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.orchestrator.workersName }}
  minReplicas: {{ .Values.orchestrator.hpa.minReplicas }}
  maxReplicas: {{ .Values.orchestrator.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.orchestrator.hpa.targetCPUUtilizationPercentage }}
{{- end }}
