{{- if .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ectusr2.serviceAccountName" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ectusr2-role
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get","list","watch","patch","create","update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ectusr2-rb
subjects:
  - kind: ServiceAccount
    name: {{ include "ectusr2.serviceAccountName" . }}
roleRef:
  kind: Role
  name: ectusr2-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
