name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Cargo cache
        uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build --release
      - name: Test
        run: cargo test --all
      - name: Clippy
        run: cargo clippy --all-targets -- -D warnings
      - name: Fmt
        run: cargo fmt --all -- --check

  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Install cargo-audit
        run: cargo install cargo-audit
      - name: Cargo audit
        run: cargo audit --ignore RUSTSEC-2020-0071 || true

